name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      # Supabase environment variables from GitHub secrets
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      # Stripe environment variables from GitHub secrets
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4 # Explicitly specify the version
      - run: pnpm --version
        name: Validate pnpm Installation
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'
      - run: pnpm install --no-frozen-lockfile
      # - run: pnpm lint  # Temporarily disabled while fixing linting issues
      - run: pnpm build
      # Removed pnpm test since most packages don't have tests defined
      - run: pnpm test:e2e