name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4 # Explicitly specify the version
      - run: pnpm --version
        name: Validate pnpm Installation
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install --no-frozen-lockfile
      # - run: pnpm lint  # Temporarily disabled while fixing linting issues
      - run: pnpm build
      - run: pnpm test
      - run: pnpm test:e2e